# Generated by Django 6.0.2 on 2026-03-03 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('section_type', models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission'), ('values', 'Core Values')], max_length=20, unique=True)),
                ('title_en', models.CharField(max_length=100)),
                ('title_sw', models.CharField(max_length=100)),
                ('content_en', models.TextField()),
                ('content_sw', models.TextField()),
                ('icon', models.CharField(default='bi-eye', help_text='Bootstrap icon class', max_length=50)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('name_en', models.CharField(max_length=100)),
                ('name_sw', models.CharField(max_length=100)),
                ('address_en', models.TextField()),
                ('address_sw', models.TextField()),
                ('postal_box', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_main', models.BooleanField(default=False)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('title_en', models.CharField(max_length=200)),
                ('title_sw', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_sw', models.TextField()),
                ('badge_text_en', models.CharField(max_length=100)),
                ('badge_text_sw', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (if no image uploaded)')),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('phone', models.CharField(default='+255 788 775 282', max_length=20)),
                ('whatsapp', models.CharField(default='+255 788 775 282', max_length=20)),
                ('email', models.EmailField(default='agtarimo@gmail.com', max_length=254)),
                ('working_hours_en', models.CharField(default='Mon-Sat 8:00-20:00 | Sun 8:30-20:00', max_length=100)),
                ('working_hours_sw', models.CharField(default='Jumatatu-Jumamosi 8:00-20:00 | Jumapili 8:30-20:00', max_length=100)),
                ('notice_en', models.CharField(default='WhatsApp/SMS/Voice calls accepted during working hours only', max_length=200)),
                ('notice_sw', models.CharField(default='WhatsApp/SMS/Simu hupokelewa wakati wa saa za kazi tu', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='CoreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('icon', models.CharField(default='bi-bank2', help_text='Bootstrap icon class', max_length=50)),
                ('title_en', models.CharField(max_length=100)),
                ('title_sw', models.CharField(max_length=100)),
                ('description_en', models.CharField(max_length=300)),
                ('description_sw', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Core Service',
                'verbose_name_plural': 'Core Services',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('question_en', models.CharField(max_length=300)),
                ('question_sw', models.CharField(max_length=300)),
                ('answer_en', models.TextField()),
                ('answer_sw', models.TextField()),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('company_name', models.CharField(default='KALTON INVESTMENT', max_length=100)),
                ('registration_en', models.CharField(max_length=200)),
                ('registration_sw', models.CharField(max_length=200)),
                ('address_en', models.TextField()),
                ('address_sw', models.TextField()),
                ('copyright_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('tagline_en', models.CharField(default='Trusted Banking & Mobile Money Agent · Est. 2022', max_length=200)),
                ('tagline_sw', models.CharField(default='Wakala wa Benki na Pesa kwa Simu · Ilianzishwa 2022', max_length=200)),
                ('heading_en', models.CharField(default='Your Trusted Mobile Money & Banking Agent', max_length=200)),
                ('heading_sw', models.CharField(default='Wakala Wako wa Pesa kwa Simu na Benki Anayeaminika', max_length=200)),
                ('subheading_en', models.TextField(default='Fast, secure & reliable financial services in Dodoma. Banking, mobile money & international money transfers under one roof.', max_length=500)),
                ('subheading_sw', models.TextField(default='Huduma za kifedha za haraka, salama na za kuaminika Dodoma. Benki, pesa kwa simu na uhamisho wa fedha kimataifa chini ya paa moja.', max_length=500)),
                ('registration_text_en', models.CharField(default='Reg: 17th May 2022', max_length=100)),
                ('registration_text_sw', models.CharField(default='Sajili: 17 Mei 2022', max_length=100)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='MobileOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Mobile Money Operator',
                'verbose_name_plural': 'Mobile Money Operators',
            },
        ),
        migrations.CreateModel(
            name='PartnerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(default='Commercial Bank', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
            ],
            options={
                'verbose_name': 'Partner Bank',
                'verbose_name_plural': 'Partner Banks',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(help_text='Bootstrap icon class', max_length=50)),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='TransferPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
            ],
            options={
                'verbose_name': 'Transfer Partner',
                'verbose_name_plural': 'Transfer Partners',
            },
        ),
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('count', models.IntegerField(default=1234)),
                ('text_en', models.CharField(default='and counting...', max_length=50)),
                ('text_sw', models.CharField(default='na zinaendelea...', max_length=50)),
            ],
            options={
                'verbose_name': 'Visitor Counter',
                'verbose_name_plural': 'Visitor Counter',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kalton Investment', max_length=100)),
                ('primary_color', models.CharField(default='#f5b342', max_length=20)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
            ],
            options={
                'verbose_name': 'Website Setting',
                'verbose_name_plural': 'Website Settings',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('street_address_en', models.CharField(max_length=200)),
                ('street_address_sw', models.CharField(max_length=200)),
                ('landmark_en', models.TextField(blank=True)),
                ('landmark_sw', models.TextField(blank=True)),
                ('google_maps_embed_url', models.URLField(blank=True, max_length=500)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_details', to='website.branch')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
