# Generated by Django 6.0.2 on 2026-03-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('title_en', models.CharField(default='YOUR TRUSTED BANKING & MOBILE MONEY AGENT', max_length=200)),
                ('title_sw', models.CharField(default='WAKALA WAKO WA BENKI NA PESA KWA SIMU', max_length=200)),
                ('description_en', models.CharField(default='Banking, mobile money and international money transfers – Nzuguni, Dodoma', max_length=300)),
                ('description_sw', models.CharField(default='Huduma za kibenki, mitandao ya simu na uhamisho wa fedha kimataifa – Nzuguni, Dodoma', max_length=300)),
                ('button_text_en', models.CharField(default='Contact Us', max_length=50)),
                ('button_text_sw', models.CharField(default='Wasiliana Nasi', max_length=50)),
                ('button_link', models.CharField(default='#contact', help_text='URL or anchor link', max_length=200)),
                ('button_icon', models.CharField(default='bi-whatsapp', help_text='Bootstrap icon class', max_length=50)),
                ('background_color', models.CharField(default='#0b1423', help_text='Background color code', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color code', max_length=20)),
                ('accent_color', models.CharField(default='#f5b342', help_text='Accent color for title', max_length=20)),
            ],
            options={
                'verbose_name': 'Promotional Block',
                'verbose_name_plural': 'Promotional Blocks',
            },
        ),
    ]
